github: [UltraInstinct0x]  # Supporting the grind fr fr
ko_fi: smolswarms      # Buy us a coffee because sleep is for the weak
custom: ["https://smolswarms.ai/sponsor"]  # For when you're feeling extra generous no cap
