[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "smolswarms"
version = "0.1.0"
description = "Spawn and orchestrate autonomous AI agent swarms that actually do be hitting different fr fr"
readme = "README.md"
license = "MIT"
requires-python = ">=3.10"  # Bumped up to match smolagents' energy
authors = [
    { name = "Gokhan Guney", email = "your.email@example.com" },
]
dependencies = [
    "smolagents>=1.1.0.dev0",  # Fresh from the repo
    "pydantic>=2.0.0",
    "rich>=13.9.4",  # Matching smolagents' version for that consistent drip
    "typer>=0.9.0",
]

[project.optional-dependencies]
dev = [
    "pytest>=8.1.0",  # Updated to match smolagents test deps
    "pytest-cov>=4.0.0",
    "black>=23.0.0",
    "ruff>=0.5.0",  # Bumped to match smolagents
    "mypy>=1.0.0",
    "types-all",
]

[tool.black]
line-length = 88
target-version = ['py310']  # Updated for that 3.10 life

[tool.ruff]
line-length = 88
target-version = "py310"

[tool.mypy]
python_version = "3.10"
warn_return_any = true
warn_unused_configs = true
disallow_untyped_defs = true