name: 🚀 Feature request
description: Suggest an idea that would make this framework go even harder
title: "[Feature]: "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this feature request! Let's make AI swarms even more based.
        
  - type: textarea
    id: problem
    attributes:
      label: Is your feature request related to a problem?
      description: What's the pain point you're trying to solve?
      placeholder: "I'm always frustrated when my agents can't [...]"
    validations:
      required: true
      
  - type: textarea
    id: solution
    attributes:
      label: Describe the solution you'd like
      description: What should the feature do?
      placeholder: "The agents should be able to [...]"
    validations:
      required: true
      
  - type: textarea
    id: alternatives
    attributes:
      label: Describe alternatives you've considered
      description: What other approaches could work?
      
  - type: dropdown
    id: priority
    attributes:
      label: Priority
      options:
        - Critical (breaks core functionality)
        - High (major improvement)
        - Medium (nice to have)
        - Low (would be cool)
    validations:
      required: true
      
  - type: textarea
    id: context
    attributes:
      label: Additional context
      description: Add any other context, code examples, or references for the feature