name: 🚀 Feature Request
description: Suggest a feature that's more fire than a RGB gaming setup
title: "feat: "
labels: ["enhancement", "fix-me"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for dropping this feature request fr fr! Let's make SmolSwarms more cracked than ever 🔥

  - type: textarea
    id: feature-description
    attributes:
      label: 📝 Feature Description
      description: Tell us what kind of feature would make SmolSwarms hit even more different
      placeholder: "I want SmolSwarms to be able to..."
    validations:
      required: true

  - type: textarea
    id: proposed-solution
    attributes:
      label: 💡 Proposed Solution
      description: Drop your galaxy brain ideas on how to implement this
      placeholder: "We could..."
    validations:
      required: true

  - type: textarea
    id: code-example
    attributes:
      label: 🧑‍💻 Usage Example
      description: Show us how you'd want to use this feature (the more cursed the better)
      render: python
      placeholder: |
        from smolswarms import SwarmFactory

        # Your absolutely cracked example here
        swarm = SwarmFactory().spawn_hivemind(
            vibe_check=True,
            power_level="over9000"
        )
    validations:
      required: false

  - type: dropdown
    id: priority
    attributes:
      label: 🎯 Priority
      description: How urgently do we need this to go brrr?
      options:
        - "🐌 Low: Would be nice to have"
        - "🚶‍♂️ Medium: Pretty useful fr fr"
        - "🏃‍♂️ High: Need this ASAP no cap"
        - "🚀 Critical: System literally unusable without it"
    validations:
      required: true

  - type: checkboxes
    id: terms
    attributes:
      label: 📜 Guidelines
      description: By submitting this issue, you agree to the following
      options:
        - label: I checked existing issues to avoid dropping duplicate requests
          required: true
        - label: I added enough context for @openhands-agent to understand the vibe
          required: true
