# Site settings
title: SmolSwarms
description: A Python library for building and coordinating swarms of AI agents that hit different fr fr 🤖
theme: just-the-docs

url: https://gokhanguney.github.io/smolswarms

aux_links:
  "SmolSwarms on GitHub":
    - "https://github.com/gokhanguney/smolswarms"

# Enable or disable the site search
search_enabled: true

# Set the search token separator
search_tokenizer_separator: /[\s/]+/

# Enable or disable heading anchors
heading_anchors: true

# Color scheme
color_scheme: dark

# Callouts
callouts:
  warning:
    title: Warning
    color: red
  note:
    title: Note
    color: blue
  tip:
    title: Pro Tip
    color: green

# Footer content
footer_content: "Made with 💜 by <a href=\"mailto:g_guney@icloud.com\">@gokhanguney</a>"

# Back to top link
back_to_top: true
back_to_top_text: "Back to top"

# Footer "Edit this page on GitHub" link text
gh_edit_link: true
gh_edit_link_text: "Edit this page on GitHub"
gh_edit_repository: "https://github.com/gokhanguney/smolswarms"
gh_edit_branch: "main"
gh_edit_source: docs
gh_edit_view_mode: "tree"
